### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by Fl0GUI** [strem-app/StreamElements.WebSocket.Reactive#1]
I was trying to set up my own websocket connection to streamelements but the url of their documentation seemed outdated. The url I found in the StreamElementsClient.cs file worked immediately, so I just wanted to thank you for your efforts.

Would you care to explain how you found that url? I'm very interested!

**Comment by grofit** [comment]
Hey I think that came from the original library I made a custom fork from:
https://github.com/swiftyspiffy/StreamElementsNET/blob/master/StreamElementsNET/StreamElementsNET/Client.cs#L10

From what I remember I used their library but had to make some PRs but the PRs were not actioned:
https://github.com/swiftyspiffy/StreamElementsNET/pull/6
https://github.com/swiftyspiffy/StreamElementsNET/pull/5

So I just had to base my work off the fork, which I then wrapped with the rx layer, I only really have a working knowledge of their APIs but it was enough to make the changes I needed.
